## dumb makefile

sysman: system_management_server.c
	gcc system_management_server.c -o system_management_server -std=c99

zone:
	gcc aggregate_detect.c -o aggregate_detect -std=c99

clean:
	rm -rf system_management_server
	rm -rf aggregate_detect